# Use default configuration
globs:
  - "**/*.md"
  - "!node_modules/**"
  - "!vendor/**"
  - "!legacy/**/*.md"
  - "!docs/development/**/*.md"

# Fix issues automatically where possible
fix: true

# Configure output formatter
outputFormatters:
  - markdownlint-cli2-formatter-default
