# Use default configuration
config:
  default: true
  MD013: false  # Line length
  MD024:
    siblings_only: true  # Allow duplicate headings in different sections
  MD029: false  # Ordered list item prefix
  MD040: true  # Fenced code blocks should have a language specified
  MD032: true  # Lists should be surrounded by blank lines
  MD014: false  # Dollar signs in shell code blocks
  MD046:
    style: consistent  # Code block style

globs:
  - "**/*.md"
  - "!node_modules/**"
  - "!vendor/**"

# Fix issues automatically where possible
fix: true
