name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Clear known_hosts
        run: rm -f ~/.ssh/known_hosts

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure target directory exists
        run: |
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} "
            mkdir -p ${{ secrets.DEPLOY_PATH }}
          "

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='.gitignore' \
          --exclude='README.md' \
          ./ ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/

      - name: Set correct file permissions
        run: |
          ssh ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }} "
            chmod -R 755 ${{ secrets.DEPLOY_PATH }} &&
            find ${{ secrets.DEPLOY_PATH }} -type f -exec chmod 644 {} \;
          "
